### ISSUE TITLE
Starting Home World option

### ISSUE THREAD

**Issue by Pelldom** [ekolis/FrEee#220]
**What do you want to see?**
When creating a new game, the Home World Size field shows ALL possible planet sizes, including Constructed planet sizes (ring world and sphere worlds), however, any Constructed planet sizes give an error and are not valid options for homeworlds.

Perhaps a flag that can set certain planet sizes as valid Home World size.

**How would it help players?**
Would allow certain planet sizes (eg FQM special types) to be excluded as potential home worlds and Constructed planets (ring world and sphere worlds) becoming valid home world options.

**Alternatives**
new flag/field "Allowed home world size"

**Things to consider**
Example:
FrEee Fusion mod has planet sizes ranging from Type 1 to Type 24. Types 1 through 5 cannot be gas giants and Types 21-24 are only Gas Giants. Excluding those from being valid homeworld sizes would be useful.

**Comment by ekolis** [comment]
I don't see why constructed planet sizes couldn't be homeworlds; I'll have to look into that error. As for sizes that can only be certain planet types such as gas giants, I suppose I could just exclude all planet size that can't be all possible types?
