### ISSUE TITLE
Homeworld facilities are selected incorrectly

### ISSUE THREAD

**Issue by cwombat169** [ekolis/FrEee#285]
**Describe the bug**
The game currently selects facilities for homeworlds at the start of the game incorrectly

**To Reproduce**
start a game

**Expected behavior**
1 spaceyard highest rate available
1 starport unless natural merchants
1 radioactives highest rate available
1 organics highest rate available
divide remaining slots between highest rate mineral and highest rate research favoring mineral if its an odd number of slots remaining

**Actual behavior**
not the way it should be

**Screenshots**
What am I made of time?

**Additional context**
you are the best Ed ^

**Comment by ekolis** [comment]
oops natural merchants should not have a spaceport!

**Comment by ekolis** [comment]
Now they don't.
