### ISSUE TITLE
Able to issue movement dependent orders to immobile objects

### ISSUE THREAD

**Issue by cwombat169** [ekolis/FrEee#296]
**Describe the bug**
You can issue move, warp, attack, evade, sentry orders to immobile objects like colonies. The game will repeatedly try to execute these orders every turn until you cancel them.

**To Reproduce**
Click on a colony
See movement order buttons available
Place an order

**Expected behavior**
These buttons should really just not appear for immobile objects

**Actual behavior**
Buttons appear and are able to issuen these nonsense orders

**Screenshots**
N/A

**Additional context**
The planets are trying to become real boys. You must stop them.

**Comment by ekolis** [comment]
I guess the idea was that they might gain the ability to move at some point in the future, and you'd want them to move at that point? But yeah, it is pretty silly.
