### ISSUE TITLE
Designs are being duplicated

### ISSUE THREAD

**Issue by ekolis** [ekolis/FrEee#64]
**Describe the bug**
Sometimes vehicle designs get duplicated when processing a turn.

**To Reproduce**
1. Create some designs
1. End your turn
1. Start a new game to load designs from the library.
1. Order some ships to be built
1. End your turn

**Expected behavior**
Designs are not duplicated

**Actual behavior**
Some of the designs are duplicated

**Screenshots**
Don't have any now

**Additional context**
Possibly related to #66

**Comment by ekolis** [comment]
Skyburn says he is getting debug messages such as "Ion Engine II is obsoleted by Ion Engine II" - maybe that is a clue? The designs are obsoleting themselves?

**Comment by Skyburn1** [comment]
[debug.txt](https://github.com/ekolis/FrEee/files/4114011/debug.txt)
Maybe this will help?

**Comment by ekolis** [comment]
Duplicate of #27
