### ISSUE TITLE
Enable C#'s new "nullable reference types" feature.

### ISSUE THREAD

**Issue by ekolis** [ekolis/FrEee#97]
**What do you want to see?**
Once #20 (.NET Core port) is implemented, we can enable nullable reference types and clean up any code where we are assuming reference types to be nullable.

**How would it help players?**
Fewer null reference exception crashes.

**Alternatives**
N/A

**Screenshots and mockups**
N/A

**Things to consider**
This will take a while to clean up all the compiler warnings; might want to mark them as errors so we don't miss any!

**Comment by ekolis** [comment]
OK, that leaves over 1200 compile errors... yikes!

**Comment by KarbonKitty** [comment]
It might be easier to start with compiler warnings and cut down on those first? I'm willing to try and tackle this, maybe with some smaller refactorings along the way, and probably eliminating outstanding warnings first (there are 58 of those in the master now, but most are from `Record.TryFindFieldValue` which is marked as `Obsolete`).

**Comment by ekolis** [comment]
Oh, I just took care of this; I left everything at warnings only for now so the code still builds and runs but we have green squiggles everywhere!
